# Generated by Django 3.2.9 on 2022-10-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call Back',
                'verbose_name_plural': 'Mpesa Call Backs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=128, verbose_name='item')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='total amount')),
                ('sub_unit', models.FloatField(default=0.0, verbose_name='sub unit')),
                ('payment_date', models.DateTimeField(null=True, verbose_name='payment date')),
                ('tax_rate', models.FloatField(default=10.0, verbose_name='tax rate')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='paid amount')),
                ('balance', models.FloatField(default=0.0, verbose_name='balance')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=40, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit card', 'Credit card'), ('Jambo Pay', 'Jambo Pay'), ('Mpesa', 'Mpesa'), ('NHIF', 'NHIF')], max_length=33, verbose_name='payment method')),
                ('payment_type', models.CharField(choices=[('Appointment', 'Appointment'), ('Lab Test', 'Lab Test'), ('Medicine', 'Medicine'), ('Ward Allortment', 'Ward Allortment')], max_length=15, verbose_name='payment type')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.TextField(verbose_name='type')),
                ('reference', models.TextField(verbose_name='reference')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone')),
                ('organization_balance', models.FloatField(default=0.0, verbose_name='organization balance')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit card', 'Credit card'), ('Jambo Pay', 'Jambo Pay'), ('Mpesa', 'Mpesa'), ('NHIF', 'NHIF')], max_length=33, verbose_name='payment method')),
                ('invoiced_date', models.DateTimeField(null=True, verbose_name='invoiced date')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='total amount')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='paid amount')),
                ('balance', models.FloatField(default=0.0, verbose_name='balance')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=40, verbose_name='status')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointments')),
                ('payment', models.ManyToManyField(related_name='payments', to='billing.Payment')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
