# Generated by Django 3.2.9 on 2022-05-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='organization_balance',
            field=models.FloatField(default=0.0, verbose_name='organization balance'),
        ),
    ]
