# Generated by Django 3.2.9 on 2022-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=40, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=40, verbose_name='status'),
        ),
    ]
