# Generated by Django 3.2.9 on 2022-05-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_organization_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
    ]
