# Generated by Django 3.2.9 on 2022-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit card', 'Credit card'), ('Jambo Pay', 'Jambo Pay'), ('Mpesa', 'Mpesa'), ('NHIF', 'NHIF')], default=1, max_length=33, verbose_name='payment method'),
            preserve_default=False,
        ),
    ]
