# Generated by Django 3.2.9 on 2022-07-06 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('profile_picture', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('id_no', models.CharField(blank=True, max_length=58, null=True, verbose_name='National ID')),
                ('nationality', django_countries.fields.CountryField(default='KE', max_length=57, verbose_name='Country')),
                ('town', models.CharField(blank=True, max_length=57, null=True, verbose_name='town')),
                ('estate', models.CharField(blank=True, max_length=57, null=True, verbose_name='estate')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20, verbose_name='gender')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=20, verbose_name='marital status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('job_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job id')),
                ('available', models.BooleanField(default=False, verbose_name='available')),
                ('longitude', models.FloatField(default=36.817223, verbose_name='longitude')),
                ('latitude', models.FloatField(default=-1.286389, verbose_name='latitude')),
                ('number_plate', models.CharField(blank=True, max_length=12, null=True, verbose_name='Number plate')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_driver_departments', to='accounts.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-id'],
            },
        ),
    ]
