# Generated by Django 3.2.9 on 2022-05-17 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_fee', models.PositiveIntegerField(default=100, verbose_name='appointment fee')),
                ('appointment_date', models.DateField(default=datetime.date.today, verbose_name='appointment date')),
                ('notes', models.TextField(blank=True, help_text='Signs  & Symptoms.', null=True, verbose_name='medical notes')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='findings')),
                ('expired', models.BooleanField(default=False, verbose_name='expired')),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Cancelled', 'Cancelled'), ('Discharged', 'Discharged'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Treated', 'Treated')], default='Pending', max_length=20, verbose_name='status')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.departments')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ('-id',),
            },
        ),
    ]
