# Generated by Django 3.2.9 on 2022-10-06 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_fee', models.FloatField(default=0.0, verbose_name='appointment fee')),
                ('appointment_date', models.DateField(default=datetime.date.today, verbose_name='appointment date')),
                ('appointment_time', models.TimeField(default=datetime.time(15, 1, 31, 742477), verbose_name='appointment time')),
                ('notes', models.TextField(blank=True, help_text='Signs  & Symptoms.', null=True, verbose_name='medical notes')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='findings')),
                ('expired', models.BooleanField(default=False, verbose_name='expired')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], default='Pending', max_length=20, verbose_name='status')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('your_message', models.TextField(blank=True, help_text='Please, describe your problem.', null=True, verbose_name='your message')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.departments')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ('-appointment_date', '-appointment_time'),
            },
        ),
        migrations.CreateModel(
            name='Lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.CharField(max_length=60, unique=True, verbose_name='test')),
                ('price', models.FloatField(verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.administrator')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='prescription guidelines')),
                ('duration', models.CharField(blank=True, max_length=57, null=True, verbose_name='duration')),
                ('date_dispenced', models.DateTimeField(null=True, verbose_name='date dispenced')),
                ('prescription_date', models.DateField(default=datetime.date.today, verbose_name='prescription date')),
                ('dispenced', models.BooleanField(default=False, verbose_name='dispenced')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
            ],
            options={
                'verbose_name_plural': 'Prescription',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('tested', models.BooleanField(default=False, verbose_name='tested')),
                ('date_tested', models.DateTimeField(blank=True, null=True, verbose_name='date tested')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('results', models.TextField(blank=True, null=True, verbose_name='results')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('lab_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_technicians', to='accounts.labtech')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.lab_test')),
            ],
            options={
                'verbose_name_plural': 'Patient Test',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested', models.BooleanField(default=False, verbose_name='tested')),
                ('date_tested', models.DateTimeField(null=True, verbose_name='date tested')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('test', models.ManyToManyField(related_name='tests', to='appointments.Test')),
            ],
            options={
                'verbose_name_plural': 'Tests Cart',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.CharField(max_length=56, unique=True, verbose_name='medicine name')),
                ('price', models.FloatField(verbose_name='price')),
                ('on_stock', models.BooleanField(default=True, verbose_name='on stock')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Medication_Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('dispenced', models.BooleanField(default=False, verbose_name='dispenced')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('medication', models.ManyToManyField(related_name='medications', to='appointments.Medication')),
            ],
            options={
                'verbose_name_plural': 'Prescription Cart',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.medicine'),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.pharmacist'),
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField(default=36.817223, verbose_name='longitude')),
                ('latitude', models.FloatField(default=-1.286389, verbose_name='latitude')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('arrived', models.BooleanField(default=False, verbose_name='arrived')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('pick_up_time', models.DateTimeField(null=True, verbose_name='pick up time')),
                ('drop_off_time', models.DateTimeField(null=True, verbose_name='drop off time')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.driver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'verbose_name': 'Ambulance Booking',
                'verbose_name_plural': 'Ambulance Booking',
                'ordering': ['id'],
            },
        ),
    ]
