# Generated by Django 3.2.9 on 2022-05-27 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(9, 17, 54, 97525), verbose_name='appointment time'),
        ),
    ]
