# Generated by Django 3.2.9 on 2022-05-28 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(19, 34, 40, 259741), verbose_name='appointment time'),
        ),
    ]
