# Generated by Django 3.2.9 on 2022-05-20 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.CharField(max_length=60, unique=True, verbose_name='test')),
                ('price', models.FloatField(verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.administrator')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='prescription guidelines')),
                ('duration', models.CharField(blank=True, max_length=57, null=True, verbose_name='duration')),
                ('prescription_date', models.DateField(default=datetime.date.today, verbose_name='prescription date')),
                ('dispenced', models.BooleanField(default=False, verbose_name='dispenced')),
            ],
            options={
                'verbose_name_plural': 'Medication',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('tested', models.BooleanField(default=False, verbose_name='tested')),
                ('date_tested', models.DateTimeField(null=True, verbose_name='date tested')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('results', models.TextField(verbose_name='results')),
            ],
            options={
                'verbose_name_plural': 'Patient Test',
            },
        ),
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ('-appointment_date', '-appointment_time'), 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(13, 36, 14, 613306), verbose_name='appointment time'),
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested', models.BooleanField(default=False, verbose_name='tested')),
                ('date_tested', models.DateTimeField(null=True, verbose_name='date tested')),
                ('paid', models.BooleanField(default=False, verbose_name='dispenced')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('test', models.ManyToManyField(related_name='tests', to='appointments.Test')),
            ],
            options={
                'verbose_name_plural': 'Patient Tests',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments'),
        ),
        migrations.AddField(
            model_name='test',
            name='lab_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_technicians', to='accounts.labtech'),
        ),
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.lab_test'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.CharField(max_length=56, unique=True, verbose_name='medicine name')),
                ('price', models.FloatField(verbose_name='price')),
                ('on_stock', models.BooleanField(default=True, verbose_name='on stock')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Medication_Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('dispenced', models.BooleanField(default=False, verbose_name='dispenced')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments')),
                ('medication', models.ManyToManyField(related_name='medications', to='appointments.Medication')),
            ],
            options={
                'verbose_name_plural': 'Medication Bag',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointments'),
        ),
        migrations.AddField(
            model_name='medication',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.medicine'),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.pharmacist'),
        ),
    ]
