# Generated by Django 3.2.9 on 2022-07-06 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver'),
        ('appointments', '0003_auto_20220529_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(21, 7, 9, 240561), verbose_name='appointment time'),
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField(default=36.817223, verbose_name='longitude')),
                ('latitude', models.FloatField(default=-1.286389, verbose_name='latitude')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('arrived', models.BooleanField(default=False, verbose_name='arrived')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('pick_up_time', models.DateTimeField(null=True, verbose_name='pick up time')),
                ('drop_off_time', models.DateTimeField(null=True, verbose_name='drop off time')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.driver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.receptionist')),
            ],
            options={
                'verbose_name': 'Ambulance Booking',
                'verbose_name_plural': 'Ambulance Booking',
                'ordering': ['id'],
            },
        ),
    ]
