# Generated by Django 3.2.9 on 2022-05-22 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(8, 8, 27, 391592), verbose_name='appointment time'),
        ),
    ]
