# Generated by Django 3.2.9 on 2022-05-24 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220521_1646'),
        ('appointments', '0007_auto_20220523_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name_plural': 'Tests Cart'},
        ),
        migrations.AddField(
            model_name='test',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(12, 30, 19, 636551), verbose_name='appointment time'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
    ]
